### ISSUE TITLE
Activity: Clicking on Related Case opens a new browser tab/window

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#1]
I _think_ it should just navigate, since I don't want people to end up with lots of Goliath browser windows open.  But let me know if you think that's a bad idea.

**Comment by edWisor** [comment]
I intentionally coded it that way to make sure that people don't loose the activity page they have opened just because they want to review the case related to it. I mean there is a good chance that the person just wants to give a quick look to the related case. Should I change it? I coded it that way, because it made more sense. I can change it within minutes if you want.

**Comment by adityadigitalomnibus** [comment]
It has been done intentionally like that. The logic is very simple. If a person has opened an Activity window, he may be interested in details of that particular activity. He may open the related case just to get a glimpse of it or something. Thats why I made the cases open in new tab. If you want, I can change it within minutes.
