### ISSUE TITLE
General: Some of temporary "processing your request" windows have an X in the upper right corner.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#3]
But we don't actually expect them to click on it.  The message doesn't tell them not to click on it, or that they won't need to click on it.  Should we remove the X?  Or add some text indicating "Please wait ..."

**Comment by adityadigitalomnibus** [comment]
I think for the time they won't do any harm. Because no matter what you do with the X, the window is going to move to the next location. The command is executed according to time. It waits for 1500ms and then moves to another screen. So, please don't worry. Even if someone clicks it, it won't affect the action in some way. If you still want to change it, please point out the windows and I will remove the X.
