### ISSUE TITLE
General: Some of the "processing your request" pop-over windows come and go quite quickly.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#9]
So you see a flash of a window, but can't read it.  This would be worrisome to me.  I would think I missed something important, or accidentally did something I didn't mean to.  Especially the ones you see when you click on the Activity or Case List Icons.  Should some of them be removed (and maybe replaced with place-holder text on the page itself?)

**Comment by adityadigitalomnibus** [comment]
Which windows are you exactly talking about? Apart from loaders... Every window stays for atleast 1.5 seconds. I have programmed it in that way, Deliberately delayed them to make sure user gets a hold of the message.

**Comment by douglaswyatt** [comment]
I think it was the ones that appeared when I went to the Case or Activity list that flashed too quickly.

**Comment by adityadigitalomnibus** [comment]
Yes. They are not windows, they are page loaders. They are like a loading bar which is supposed to stay during the time the data is being called from the API. But in our case, the backend is too fast and we are usually on a good internet connection, so its going too quickly. The response time of every API is less than a second in our current platform. So, please don't get confused by that. I am not removing that page loader because it would be helpful for people with less internet speed as their response time will be higher.
